version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      networks:
        - local-keycloak
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      restart: unless-stopped
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        PROXY_ADDRESS_FORWARDING: "true"
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      #ports:
        #- 8080:8080
      depends_on:
        - mysql
      networks:
        - local-keycloak
        - traefik-public
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.services.keycloak.loadbalancer.server.port=8080
        - traefik.http.routers.keycloak.rule=Host(`auth.game-vault.net`)
        - traefik.http.routers.keycloak.entrypoints=web,websecure
        - traefik.http.routers.keycloak.tls.certresolver=myresolver
#        - traefik.http.routers.keycloak.entrypoints=web
#        - traefik.http.routers.keycloak.tls=false
#        - traefik.protocol=http
#      command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]
      volumes:
        - ./themes/gamevault:/opt/jboss/keycloak/themes/gamevault

networks:
  traefik-public:
    external: true
  local-keycloak:
